openapi: 3.0.0
info:
  title: Bookmark Manager API
  version: 1.0.0
  description: Simple bookmark management API with authentication

servers:
  - url: http://localhost:3000/api
    description: Development server
  - url: https://bookmarks.example.com/api
    description: Production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "clh1234567890abcdef"
        email:
          type: string
          format: email
          example: "user@example.com"
        name:
          type: string
          nullable: true
          example: "John Doe"
        createdAt:
          type: string
          format: date-time
          example: "2025-01-15T10:30:00Z"
      required:
        - id
        - email
        - createdAt

    Bookmark:
      type: object
      properties:
        id:
          type: string
          example: "clh9876543210abcdef"
        userId:
          type: string
          example: "clh1234567890abcdef"
        url:
          type: string
          format: uri
          example: "https://docs.anthropic.com"
        title:
          type: string
          example: "Anthropic Documentation"
        description:
          type: string
          nullable: true
          example: "Claude API reference and guides"
        favicon:
          type: string
          format: uri
          nullable: true
          example: "https://docs.anthropic.com/favicon.ico"
        tags:
          type: array
          items:
            type: string
          example: ["ai", "api", "documentation"]
        createdAt:
          type: string
          format: date-time
          example: "2025-01-15T14:20:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-01-15T14:20:00Z"
      required:
        - id
        - userId
        - url
        - title
        - tags
        - createdAt
        - updatedAt

    Error:
      type: object
      properties:
        error:
          type: string
          example: "Invalid credentials"
        code:
          type: string
          example: "UNAUTHORIZED"
      required:
        - error

paths:
  /auth/register:
    post:
      summary: Register new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: "SecurePass123!"
                name:
                  type: string
                  nullable: true
                  example: "John Doe"
              required:
                - email
                - password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Email already exists"
                code: "DUPLICATE_EMAIL"
        '422':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Password must be at least 8 characters"
                code: "VALIDATION_ERROR"

  /auth/login:
    post:
      summary: Login user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  example: "SecurePass123!"
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid email or password"
                code: "INVALID_CREDENTIALS"

  /auth/me:
    get:
      summary: Get current user
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user details
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Authentication required"
                code: "UNAUTHORIZED"

  /bookmarks:
    get:
      summary: List user's bookmarks
      tags:
        - Bookmarks
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
          description: Page number (0-indexed)
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
          description: Results per page
        - name: search
          in: query
          schema:
            type: string
          description: Search in title, URL, description
        - name: tag
          in: query
          schema:
            type: string
          description: Filter by tag
      responses:
        '200':
          description: List of bookmarks
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookmarks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Bookmark'
                  total:
                    type: integer
                    example: 42
                  page:
                    type: integer
                    example: 0
                  limit:
                    type: integer
                    example: 20
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create bookmark
      tags:
        - Bookmarks
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  example: "https://docs.anthropic.com"
                title:
                  type: string
                  example: "Anthropic Documentation"
                description:
                  type: string
                  nullable: true
                  example: "Claude API reference"
                tags:
                  type: array
                  items:
                    type: string
                  example: ["ai", "api"]
              required:
                - url
                - title
      responses:
        '201':
          description: Bookmark created
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookmark:
                    $ref: '#/components/schemas/Bookmark'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid URL format"
                code: "VALIDATION_ERROR"
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /bookmarks/{id}:
    get:
      summary: Get bookmark by ID
      tags:
        - Bookmarks
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Bookmark ID
      responses:
        '200':
          description: Bookmark details
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookmark:
                    $ref: '#/components/schemas/Bookmark'
        '404':
          description: Bookmark not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Bookmark not found"
                code: "NOT_FOUND"
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    patch:
      summary: Update bookmark
      tags:
        - Bookmarks
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Bookmark ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                title:
                  type: string
                description:
                  type: string
                  nullable: true
                tags:
                  type: array
                  items:
                    type: string
              # All fields optional for PATCH
      responses:
        '200':
          description: Bookmark updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookmark:
                    $ref: '#/components/schemas/Bookmark'
        '404':
          description: Bookmark not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete bookmark
      tags:
        - Bookmarks
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Bookmark ID
      responses:
        '204':
          description: Bookmark deleted successfully
        '404':
          description: Bookmark not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /bookmarks/tags:
    get:
      summary: Get all tags with counts
      tags:
        - Bookmarks
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of tags with usage counts
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: "typescript"
                        count:
                          type: integer
                          example: 15
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
