#!/usr/bin/env python3

"""
Sentra AI-Powered SaaS Factory - New Project Initializer

This script initializes a NEW project structure for the Sentra SaaS Factory.
It creates all necessary directories, templates, and configuration files.

Usage:
    python .sentra/scripts/init-project.py --name "project-name"

Features:
    - Creates architect session directory structure
    - Generates empty session templates
    - Creates initial coverage checklist (all 0%)
    - Creates progress tracking file
    - Provides guidance for starting with Voice Architect

Author: Glen Barnhardt with help from Claude Code
License: MIT
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List


# ANSI color codes
class Colors:
    RED = '\033[0;31m'
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    BLUE = '\033[0;34m'
    PURPLE = '\033[0;35m'
    CYAN = '\033[0;36m'
    NC = '\033[0m'  # No Color


def log_info(message: str) -> None:
    """Print info message."""
    print(f"{Colors.BLUE}ℹ {Colors.NC} {message}")


def log_success(message: str) -> None:
    """Print success message."""
    print(f"{Colors.GREEN}✓{Colors.NC} {message}")


def log_warning(message: str) -> None:
    """Print warning message."""
    print(f"{Colors.YELLOW}⚠{Colors.NC} {message}")


def log_error(message: str) -> None:
    """Print error message."""
    print(f"{Colors.RED}✗{Colors.NC} {message}")


def log_header(message: str) -> None:
    """Print section header."""
    print()
    print(f"{Colors.PURPLE}{'═' * 60}{Colors.NC}")
    print(f"{Colors.PURPLE}  {message}{Colors.NC}")
    print(f"{Colors.PURPLE}{'═' * 60}{Colors.NC}")
    print()


def validate_project_name(name: str) -> bool:
    """Validate project name format."""
    if not name:
        return False
    if not name.replace('-', '').replace('_', '').isalnum():
        return False
    if len(name) < 3 or len(name) > 50:
        return False
    return True


def create_directory_structure(project_name: str, base_dir: Path) -> Dict[str, Path]:
    """Create the complete directory structure for a new project."""
    log_header("Creating Directory Structure")

    directories = {
        'architect_root': base_dir / 'architect-sessions' / project_name,
        'sessions': base_dir / 'architect-sessions' / project_name / 'sessions',
        'specs': base_dir / 'architect-sessions' / project_name / 'specs',
        'coverage': base_dir / 'architect-sessions' / project_name / 'coverage',
        'docs_specs': Path('docs') / 'specs' / project_name,
        'docs_screens': Path('docs') / 'specs' / project_name / 'screens',
        'docs_components': Path('docs') / 'specs' / project_name / 'components',
    }

    for name, path in directories.items():
        try:
            path.mkdir(parents=True, exist_ok=True)
            log_success(f"Created {path}")
        except Exception as e:
            log_error(f"Failed to create {path}: {e}")
            sys.exit(1)

    return directories


def create_session_templates(project_name: str, dirs: Dict[str, Path]) -> None:
    """Create empty session template files."""
    log_header("Creating Session Templates")

    session_dir = dirs['sessions']

    # Session 1: Initial Architecture
    session_1 = session_dir / 'session-001-initial-architecture.md'
    session_1_content = f"""# {project_name} - Session 1: Initial Architecture

**Date:** {datetime.now().strftime('%Y-%m-%d')}
**Phase:** Architecture & Planning
**Skill:** Voice Architect

## Session Goals

1. Define project requirements and goals
2. Design high-level architecture
3. Identify core features and user stories
4. Create component hierarchy
5. Plan database schema

## Requirements

<!-- Voice Architect will fill this in during conversation -->

## Architecture Decisions

<!-- Voice Architect will document decisions here -->

## Component Hierarchy

<!-- Voice Architect will create component tree here -->

## Database Schema

<!-- Voice Architect will design schema here -->

## Next Steps

<!-- Voice Architect will outline next session goals -->

---

**Generated by:** Sentra AI-Powered SaaS Factory
**Session Status:** Not Started
"""

    try:
        session_1.write_text(session_1_content)
        log_success(f"Created session template: {session_1.name}")
    except Exception as e:
        log_error(f"Failed to create session template: {e}")


def create_coverage_checklist(project_name: str, dirs: Dict[str, Path]) -> None:
    """Create initial coverage checklist with all 0% coverage."""
    log_header("Creating Coverage Checklist")

    coverage_file = dirs['coverage'] / 'coverage-checklist.yml'
    coverage_content = f"""# {project_name} - Test Coverage Checklist
#
# This file tracks test coverage for each feature as it's implemented.
# Coverage thresholds are enforced by CI/CD:
#   - Overall: 75%+
#   - Business Logic (src/services/): 90%+
#   - Utilities (src/utils/): 90%+
#   - UI Components: 60%+

project: {project_name}
created: {datetime.now().isoformat()}
updated: {datetime.now().isoformat()}

coverage:
  overall: 0%
  services: 0%
  utils: 0%
  components: 0%

features: []
  # Example structure:
  # - name: user-authentication
  #   coverage: 0%
  #   status: not_started
  #   tests:
  #     - file: tests/unit/services/auth.test.ts
  #       coverage: 0%
  #     - file: tests/integration/auth.test.ts
  #       coverage: 0%

thresholds:
  overall: 75
  services: 90
  utils: 90
  components: 60

violations: []
  # Will be populated if coverage falls below thresholds

last_check: {datetime.now().isoformat()}
"""

    try:
        coverage_file.write_text(coverage_content)
        log_success(f"Created coverage checklist: {coverage_file.name}")
    except Exception as e:
        log_error(f"Failed to create coverage checklist: {e}")


def create_progress_file(project_name: str, dirs: Dict[str, Path]) -> None:
    """Create initial progress tracking file."""
    log_header("Creating Progress Tracker")

    progress_file = dirs['architect_root'] / 'progress.json'

    progress_data = {
        'project': project_name,
        'created': datetime.now().isoformat(),
        'updated': datetime.now().isoformat(),
        'status': 'initialized',
        'phase': 'planning',
        'sessions': {
            'total': 0,
            'completed': 0,
            'current': None
        },
        'features': [],
        'milestones': [
            {
                'name': 'Architecture Design',
                'status': 'not_started',
                'sessions': []
            },
            {
                'name': 'Core Features',
                'status': 'not_started',
                'sessions': []
            },
            {
                'name': 'Testing & Quality',
                'status': 'not_started',
                'sessions': []
            },
            {
                'name': 'Deployment',
                'status': 'not_started',
                'sessions': []
            }
        ],
        'metrics': {
            'coverage': 0,
            'files_created': 0,
            'tests_written': 0,
            'features_completed': 0
        }
    }

    try:
        with progress_file.open('w') as f:
            json.dump(progress_data, f, indent=2)
        log_success(f"Created progress tracker: {progress_file.name}")
    except Exception as e:
        log_error(f"Failed to create progress tracker: {e}")


def create_readme(project_name: str, dirs: Dict[str, Path]) -> None:
    """Create project-specific README."""
    log_header("Creating Project README")

    readme_file = dirs['architect_root'] / 'README.md'
    readme_content = f"""# {project_name}

**Created:** {datetime.now().strftime('%Y-%m-%d')}
**Status:** Planning Phase
**Factory:** Sentra AI-Powered SaaS Factory

## Overview

<!-- Voice Architect will fill in project description -->

## Architecture

<!-- Voice Architect will document architecture decisions -->

## Features

<!-- Features will be added as they're designed -->

## Development

### Session History

Sessions are tracked in `./sessions/`:
- Each session is numbered sequentially
- Voice Architect documents decisions and progress
- Session files are loaded into Skill memory automatically

### Coverage

Coverage is tracked in `./coverage/coverage-checklist.yml`:
- Overall: 0% (target: 75%)
- Services: 0% (target: 90%)
- Utils: 0% (target: 90%)
- Components: 0% (target: 60%)

### Progress

Current progress is tracked in `./progress.json`:
- Phase: Planning
- Sessions: 0 completed
- Features: 0 implemented

## Getting Started

1. Start Voice Architect:
   ```bash
   claude
   > Enable Voice Architect Skill
   ```

2. Begin first session:
   ```
   I want to start Session 1 for {project_name}.
   Let's define the requirements and architecture.
   ```

3. Voice Architect will:
   - Ask about your product vision
   - Design the architecture
   - Create component hierarchy
   - Document everything in session-001-initial-architecture.md

## Next Steps

- [ ] Complete Session 1: Initial Architecture
- [ ] Review and approve architecture
- [ ] Begin Session 2: Core Feature Implementation
- [ ] Set up CI/CD pipeline
- [ ] Deploy MVP

---

**Powered by:** Sentra AI-Powered SaaS Factory
**Documentation:** .sentra/README.md
"""

    try:
        readme_file.write_text(readme_content)
        log_success(f"Created project README: {readme_file.name}")
    except Exception as e:
        log_error(f"Failed to create README: {e}")


def print_next_steps(project_name: str) -> None:
    """Print guidance for starting with Voice Architect."""
    log_header("Project Initialized! 🚀")

    print(f"{Colors.GREEN}Project '{project_name}' is ready to build!{Colors.NC}")
    print()
    print(f"{Colors.CYAN}Next Steps:{Colors.NC}")
    print()
    print(f"{Colors.YELLOW}1. Start Voice Architect:{Colors.NC}")
    print("   claude")
    print("   > Enable Voice Architect Skill")
    print()
    print(f"{Colors.YELLOW}2. Begin First Session:{Colors.NC}")
    print(f"   I want to start Session 1 for {project_name}.")
    print("   Let's define the requirements and architecture.")
    print()
    print(f"{Colors.YELLOW}3. Voice Architect Will:{Colors.NC}")
    print("   - Ask about your product vision and goals")
    print("   - Design the high-level architecture")
    print("   - Create component hierarchy")
    print("   - Plan database schema")
    print("   - Document everything in session files")
    print()
    print(f"{Colors.YELLOW}4. Review Session Output:{Colors.NC}")
    print(f"   .sentra/architect-sessions/{project_name}/sessions/session-001-initial-architecture.md")
    print()
    print(f"{Colors.CYAN}Project Structure:{Colors.NC}")
    print(f"  .sentra/architect-sessions/{project_name}/")
    print("    ├── sessions/              # Session history")
    print("    ├── specs/                 # Generated specs")
    print("    ├── coverage/              # Coverage tracking")
    print("    ├── progress.json          # Progress tracker")
    print("    └── README.md              # Project overview")
    print()
    print(f"{Colors.GREEN}Happy building! 🎨{Colors.NC}")
    print()


def main():
    """Main execution function."""
    parser = argparse.ArgumentParser(
        description='Initialize a new Sentra project'
    )
    parser.add_argument(
        '--name',
        required=True,
        help='Project name (e.g., "bookmark-manager")'
    )

    args = parser.parse_args()
    project_name = args.name

    # Header
    print()
    print(f"{Colors.PURPLE}╔{'═' * 58}╗{Colors.NC}")
    print(f"{Colors.PURPLE}║{' ' * 58}║{Colors.NC}")
    print(f"{Colors.PURPLE}║  Sentra Project Initializer - New Project{' ' * 15}║{Colors.NC}")
    print(f"{Colors.PURPLE}║{' ' * 58}║{Colors.NC}")
    print(f"{Colors.PURPLE}╚{'═' * 58}╝{Colors.NC}")
    print()

    # Validate project name
    if not validate_project_name(project_name):
        log_error("Invalid project name")
        log_info("Requirements:")
        print("  - 3-50 characters")
        print("  - Letters, numbers, hyphens, underscores only")
        print("  - Example: 'bookmark-manager', 'task_tracker'")
        sys.exit(1)

    log_success(f"Project name: {project_name}")

    # Get base directory
    base_dir = Path('.sentra')
    if not base_dir.exists():
        log_error(f"Sentra directory not found: {base_dir}")
        log_info("Run: ./scripts/setup-sentra.sh")
        sys.exit(1)

    # Check if project already exists
    project_dir = base_dir / 'architect-sessions' / project_name
    if project_dir.exists():
        log_error(f"Project already exists: {project_name}")
        log_info(f"Location: {project_dir}")
        sys.exit(1)

    # Create project structure
    dirs = create_directory_structure(project_name, base_dir)
    create_session_templates(project_name, dirs)
    create_coverage_checklist(project_name, dirs)
    create_progress_file(project_name, dirs)
    create_readme(project_name, dirs)

    # Print next steps
    print_next_steps(project_name)


if __name__ == '__main__':
    main()
